import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  fontLoadingScreen: {
    flex: 1,
    backgroundColor: "#0a2a3a",
  },
  container: {
    flex: 1,
    backgroundColor: "#0a2a3a",
    paddingHorizontal: 16,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(6, 20, 30, 0.48)",
  },
  header: {
    paddingTop: 12,
    paddingBottom: 10,
  },
  homeHeader: {
    alignItems: "center",
  },
  homeSubtitleRow: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  bookButton: {
    minWidth: 26,
    minHeight: 26,
    paddingHorizontal: 2,
    paddingVertical: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  bookButtonIcon: {
    fontSize: 22,
  },
  homeTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  homeHeaderThumb: {
    width: 42,
    height: 42,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
  },
  settingsScroll: {
    flex: 1,
  },
  settingsContent: {
    paddingBottom: 18,
  },
  title: {
    color: "#d0b86f",
    fontSize: 46,
    letterSpacing: 2,
    fontFamily: "Butcherman-Regular",
  },
  subtitle: {
    color: "#f5f266",
    fontSize: 20,
    fontFamily: "Butcherman-Regular",
  },
  homeTitle: {
    textAlign: "center",
  },
  homeSubtitle: {
    color: "#f5f266",
    fontSize: 20,
    fontFamily: "Butcherman-Regular",
    letterSpacing: 0.4,
    textAlign: "center",
  },
  infoCard: {
    borderWidth: 1,
    borderColor: "#d2d8df",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  infoText: {
    color: "#f0f6ff",
    fontSize: 16,
    fontWeight: "600",
  },
  infoNumber: {
    color: "#f6ef5d",
    fontSize: 18,
    fontWeight: "900",
  },
  setupWarningBox: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#f8cf77",
    borderRadius: 10,
    padding: 8,
    backgroundColor: "rgba(80, 45, 10, 0.35)",
  },
  setupWarningTitle: {
    color: "#ffd27d",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 4,
  },
  setupWarningText: {
    color: "#ffe8b3",
    fontSize: 12,
    lineHeight: 16,
  },
  setupHintBox: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#8cc2f3",
    borderRadius: 10,
    padding: 8,
    backgroundColor: "rgba(10, 36, 65, 0.35)",
  },
  setupHintTitle: {
    color: "#b7ddff",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 4,
  },
  setupHintText: {
    color: "#d9ecff",
    fontSize: 12,
    lineHeight: 16,
  },
  roleListView: {
    flex: 1,
  },
  roleList: {
    paddingBottom: 8,
    paddingHorizontal: 2,
  },
  roleRow: {
    alignItems: "flex-start",
    justifyContent: "space-between",
    columnGap: 6,
    marginBottom: 8,
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
  },
  roleCard: {
    width: "49.1%",
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#f6ef5d",
    borderRadius: 10,
    padding: 5,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  roleCardSpacer: {
    width: "49.1%",
  },
  roleImage: {
    width: "48%",
    aspectRatio: 0.73,
    height: 76,
    borderRadius: 7,
    marginBottom: 1,
    alignSelf: "center",
    overflow: "hidden",
  },
  roleSelected: {
    borderColor: "#f6ef5d",
    backgroundColor: "rgba(21, 28, 50, 0.6)",
  },
  roleName: {
    color: "#ffffff",
    fontSize: 16,
    fontFamily: "Butcherman-Regular",
    textAlign: "center",
  },
  roleSubtitle: {
    color: "#b7c7d8",
    fontSize: 11,
    marginTop: 1,
    textAlign: "center",
  },
  roleTeam: {
    color: "#dce7ef",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 1,
    textAlign: "center",
  },
  roleCount: {
    color: "#f6ef5d",
    marginTop: 2,
    marginBottom: 2,
    fontFamily: "Butcherman-Regular",
    textAlign: "center",
  },
  roleActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
  },
  smallBtn: {
    backgroundColor: "#22394e",
    borderWidth: 1,
    borderColor: "#d0d7de",
    borderRadius: 8,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
  },
  smallBtnDisabled: {
    opacity: 0.35,
  },
  smallBtnText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "700",
  },
  clearBtn: {
    marginLeft: 1,
    flex: 1,
    backgroundColor: "#2f4f66",
    borderRadius: 8,
    paddingHorizontal: 3,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
  },
  clearBtnText: {
    color: "#fff",
    fontSize: 8,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 12,
  },
  homeActionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    marginBottom: 14,
  },
  actionButton: {
    flex: 1,
    borderWidth: 2,
    borderColor: "#dce7ef",
    borderRadius: 24,
    paddingVertical: 12,
    backgroundColor: "#173143",
    alignItems: "center",
  },
  homeActionButton: {
    flex: 1,
    minHeight: 62,
    borderWidth: 3,
    borderColor: "#e7edf2",
    borderRadius: 34,
    paddingHorizontal: 8,
    backgroundColor: "#1f3648",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#04131d",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  homePlayButton: {
    backgroundColor: "#243b4f",
  },
  homeActionButtonDisabled: {
    opacity: 0.45,
  },
  secondaryButton: {
    borderWidth: 2,
    borderColor: "#dce7ef",
    borderRadius: 24,
    paddingVertical: 12,
    backgroundColor: "#173143",
    alignItems: "center",
    marginVertical: 14,
  },
  settingsActionSecondary: {
    marginTop: 8,
    marginBottom: 12,
  },
  stopButton: {
    borderWidth: 2,
    borderColor: "#dce7ef",
    borderRadius: 24,
    paddingVertical: 12,
    backgroundColor: "#4f2633",
    alignItems: "center",
    marginBottom: 12,
  },
  buttonText: {
    color: "#fff",
    fontSize: 20,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontFamily: "Butcherman-Regular",
  },
  homeButtonText: {
    color: "#f8fbff",
    fontSize: 15,
    letterSpacing: 0.2,
    textAlign: "center",
    fontFamily: "Butcherman-Regular",
  },
  guideBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 8, 14, 0.78)",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 20,
  },
  guideModal: {
    maxHeight: "90%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(215, 227, 238, 0.3)",
    backgroundColor: "#0e2433",
    overflow: "hidden",
  },
  guideHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(215, 227, 238, 0.2)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  guideTitle: {
    color: "#f6ef5d",
    fontSize: 22,
    fontFamily: "Butcherman-Regular",
    letterSpacing: 0.3,
  },
  guideCloseButton: {
    borderWidth: 1,
    borderColor: "#dce7ef",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  guideCloseButtonText: {
    color: "#f7fbff",
    fontSize: 13,
    fontWeight: "700",
  },
  guideScroll: {
    maxHeight: "100%",
  },
  guideScrollContent: {
    padding: 12,
    paddingBottom: 22,
    gap: 10,
  },
  guideRoleCard: {
    borderWidth: 1,
    borderColor: "rgba(246, 239, 93, 0.45)",
    borderRadius: 12,
    backgroundColor: "rgba(5, 17, 26, 0.55)",
    padding: 10,
  },
  guideRoleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  guideRoleImage: {
    width: 44,
    height: 58,
  },
  guideRoleHeaderText: {
    flex: 1,
  },
  guideRoleName: {
    color: "#ffffff",
    fontSize: 20,
    fontFamily: "Butcherman-Regular",
  },
  guideRoleSubtitle: {
    color: "#b9c7d5",
    fontSize: 12,
  },
  guideLabel: {
    marginTop: 5,
    color: "#f6ef5d",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  guideBodyText: {
    marginTop: 2,
    color: "#e8f1f8",
    fontSize: 13,
    lineHeight: 18,
  },
  card: {
    borderWidth: 1,
    borderColor: "#d2d8df",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  cardLabel: {
    color: "#fff",
    fontSize: 17,
    fontFamily: "Butcherman-Regular",
  },
  helperText: {
    color: "#c7d6e5",
    fontSize: 12,
    lineHeight: 17,
    marginTop: -2,
    marginBottom: 10,
  },
  aboutText: {
    color: "#f0f6ff",
    marginTop: 10,
    fontSize: 15,
    fontWeight: "600",
  },
  aboutSubtext: {
    color: "#c7d6e5",
    marginTop: 4,
    fontSize: 13,
  },
  trackTestButton: {
    marginTop: 10,
    borderWidth: 2,
    borderColor: "#dce7ef",
    borderRadius: 16,
    paddingVertical: 10,
    backgroundColor: "#173143",
    alignItems: "center",
  },
  trackTestButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontFamily: "Butcherman-Regular",
  },
  trackAudioMessage: {
    marginTop: 8,
    color: "#c7d6e5",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 16,
  },
  counterRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counterBtn: {
    borderWidth: 1,
    borderColor: "#dce7ef",
    borderRadius: 8,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#173143",
  },
  counterText: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "700",
    fontFamily: "Butcherman-Regular",
  },
  counterValue: {
    color: "#f6ef5d",
    fontSize: 20,
    fontWeight: "800",
    fontFamily: "Butcherman-Regular",
  },
  duckingValueText: {
    color: "#f6ef5d",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    maxWidth: "68%",
    lineHeight: 18,
    fontFamily: "Butcherman-Regular",
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  voicePickerLabel: {
    color: "#d7e4f2",
    fontSize: 14,
    marginTop: 2,
    marginBottom: 8,
    fontWeight: "600",
  },
  voiceOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  voiceOptionButton: {
    borderWidth: 1,
    borderColor: "#dce7ef",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "#173143",
    maxWidth: "100%",
  },
  voiceOptionButtonActive: {
    backgroundColor: "#f6ef5d",
    borderColor: "#f6ef5d",
  },
  voiceOptionText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  voiceOptionTextActive: {
    color: "#0f2230",
  },
  voiceHintText: {
    color: "#c7d6e5",
    marginTop: 8,
    fontSize: 12,
  },
  voiceTestButton: {
    marginTop: 10,
    borderWidth: 2,
    borderColor: "#dce7ef",
    borderRadius: 12,
    paddingVertical: 9,
    alignItems: "center",
    backgroundColor: "#173143",
  },
  voiceTestButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    fontFamily: "Butcherman-Regular",
  },
  playCard: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  playTextArea: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 0,
  },
  playFooter: {
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  bigText: {
    color: "#f6ef5d",
    fontSize: 34,
    textAlign: "center",
    fontWeight: "800",
    lineHeight: 42,
    marginBottom: 10,
    fontFamily: "Butcherman-Regular",
    width: "100%",
    flexShrink: 1,
  },
  bigTextMedium: {
    fontSize: 30,
    lineHeight: 38,
    marginBottom: 8,
  },
  bigTextSmall: {
    fontSize: 26,
    lineHeight: 33,
    marginBottom: 6,
  },
  bigTextXSmall: {
    fontSize: 20,
    lineHeight: 25,
    marginBottom: 6,
  },
  timer: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "900",
    marginBottom: 6,
    fontFamily: "Butcherman-Regular",
  },
  muted: {
    color: "#b8c7d3",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Butcherman-Regular",
  },
  warningText: {
    color: "#ffd27d",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
    fontFamily: "Butcherman-Regular",
  },
  trackRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  trackButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#dce7ef",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#173143",
  },
  trackButtonActive: {
    backgroundColor: "#f6ef5d",
    borderColor: "#f6ef5d",
  },
  trackButtonText: {
    color: "#fff",
    fontWeight: "800",
    textTransform: "uppercase",
    fontFamily: "Butcherman-Regular",
  },
  trackButtonTextActive: {
    color: "#182a39",
  },
})
